// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rreyewahgdouetcqueah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZXlld2FoZ2RvdWV0Y3F1ZWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjIxNDksImV4cCI6MjA3MTQ5ODE0OX0.A_NMV6dvSgeGF-lqh_oTcWIVbSySBVuo4FsIZ30TxRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});